name: "CI"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cs:
    name: "Code style"
    runs-on: ubuntu-latest
    steps:
      - name: "Git: checkout"
        uses: actions/checkout@v4

      - name: "PHP: setup 8.3"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: php-cs-fixer

      - name: "Composer: validate"
        run: composer validate --strict

      - name: "Composer: install"
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: "Php-CS-Fixer: version"
        run: vendor/bin/php-cs-fixer -V

      - name: "Php-CS-Fixer: check"
        run: vendor/bin/php-cs-fixer fix --diff --dry-run

  sa:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: "Git: checkout"
        uses: actions/checkout@v4

      - name: "PHP: setup 8.4"
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: phpstan

      - name: "Composer: install"
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: "PHPStan: version"
        run: phpstan --version

      - name: "PHPStan: analyze"
        run: phpstan
